[package]
name = "repokit"
version = "5.1.6"
edition = "2024"
license = "MIT"
readme = "README.md"
authors = ["Alex Figliolia"]
description = "A knowledgebase for your repository - wrapped in a CLI"
homepage = "https://github.com/alexfigliolia/repokit"
repository = "https://github.com/alexfigliolia/repokit"
keywords = ["cli", "devtool", "repository", "toolchain"]

[[bin]]
name = "repokit"
path = "internals/main.rs"

[dependencies]
jsonschema = { version = "0.49.9", default-features = false }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
colored = "3"
normalize-path = "0.2.1"
alphanumeric-sort = "1.5.8"
ignore = "0.4.33"
regex = { version = "1.13.1", features = ["std", "unicode"] }
shellexpand = "3.1.2"
schemars = "1.2.2"
futures = "0.3.33"
tokio = { version = "1.53.1", features = ["full"] }
inquire = "0.9.4"
inquire-derive = "0.9.4"
sha2 = "0.11.0"
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
