[package]
name = "repokit"
version = "5.0.3"
edition = "2024"
license = "MIT"
readme = "README.md"
authors = ["Alex Figliolia"]
description = "A knowledgebase for your repository - wrapped in a CLI"
homepage = "https://github.com/alexfigliolia/repokit"
repository = "https://github.com/alexfigliolia/repokit"
keywords = ["cli", "devtool", "repository", "toolchain"]

[[bin]]
name = "repokit"
path = "internals/main.rs"

[dependencies]
jsonschema = { version = "0.46.5", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.150"
colored = "3"
normalize-path = "0.2.1"
alphanumeric-sort = "1.5.6"
ignore = "0.4.26"
regex = { version = "1.12.3", features = ["std", "unicode"] }
shellexpand = "3.1.2"
schemars = "1.2.1"
futures = "0.3.32"
tokio = { version = "1.52.1", features = ["full"] }
inquire = "0.9.4"
inquire-derive = "0.9.4"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
