[package]
name = "repokit"
version = "1.0.5"
edition = "2024"
license = "MIT"
readme = "README.md"
authors = ["Alex Figliolia"]
homepage = "https://github.com/alexfigliolia/repokit"
repository = "https://github.com/alexfigliolia/repokit"
keywords = ["cli", "developer tool", "repository", "toolchain"]

[[bin]]
name = "repokit"
path = "internals/main.rs"

[dependencies]
jsonschema = { version = "0.46.4", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "3"
normalize-path = "0.2.1"
alphanumeric-sort = "1.5.6"
ignore = "0.4.25"
regex = { version = "1.12.3", features = ["std", "unicode"] }
shellexpand = "3.1.2"
schemars = "1.2.1"
futures = "0.3.32"
tokio = { version = "1.52.1", features = ["full"] }

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
